
package com.vodafone.ecommerce.payment.stubs;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://vodafone.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param pin
     * @param expireDate
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "validateCard", targetNamespace = "http://vodafone.com/", className = "com.vodafone.ecommerce.payment.stubs.ValidateCard")
    @ResponseWrapper(localName = "validateCardResponse", targetNamespace = "http://vodafone.com/", className = "com.vodafone.ecommerce.payment.stubs.ValidateCardResponse")
    @Action(input = "http://vodafone.com/HelloWorld/validateCardRequest", output = "http://vodafone.com/HelloWorld/validateCardResponse")
    public String validateCard(
        @WebParam(name = "cardNumber", targetNamespace = "")
        long cardNumber,
        @WebParam(name = "pin", targetNamespace = "")
        int pin,
        @WebParam(name = "expireDate", targetNamespace = "")
        String expireDate);

}
